trigger:
  branches:
    include:
      - main  # 배포할 브랜치를 지정합니다.

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - script: |
      echo Checking out GitHub repository
      git clone https://github.com/JooHoChoi/NachoBot.git  # GitHub 소유자와 저장소 이름을 입력합니다.